### ISSUE TITLE
Bug: Escape closes Sidebar 

### ISSUE THREAD

**Issue by JWO719** [ReactiveX/rxjs-docs#255]
Pressing the Escape key, closes the Sidebar, but you can't open it again

**Comment by jsonberry** [comment]
@JWO719 I was unable to reproduce this. Perhaps it was fixed, can you confirm?

**Comment by JWO719** [comment]
Hi I could reproduce it in Chrome. You just have to click on an operator and during focus you could hide the sidebar with escape. But this bug also occurs in firefox. I don't want to test it in IE but I'm quite sure there is this bug also :D

**Comment by jsonberry** [comment]
Gotcha! Okay I was able to reproduce now. Thanks!

**Comment by knittingcodemonkey** [comment]
Pressing escape to close the sidebar was intentional. We wanted the ability to skip the menu, for accessibility reasons, after you selected the option you desired. You can open it up, again, by going to the menu and selecting operators. 

The bug that does still exist is that on mobile, selecting an operator doesn't close the menu.

**Comment by jsonberry** [comment]
@knittingcodemonkey Cool, that makes sense. Glad to hear it was intentional.

As the UX stands right now:
```
As a user
Given I am on an inner operator page
And the it is not an operator at the top of the menu
And the sidenav is closed
When I select the button to open the sidenav
And I select operators
I start at the top of the list of operators 
```

Would it be better if...
```
When I select the button to open the sidenav
And I select operators
I start at the place I was at in the list of operators 
```

Re: 
> The bug that does still exist is that on mobile, selecting an operator doesn't close the menu.
I'll :eyes: for a logged issue, and I can put some effort into fixing that.

**Comment by knittingcodemonkey** [comment]
I do like the option of setting the focus, when you open the menu, to the page and/or operator on which you are currently located. 

The bug for not closing the side menu on mobile sizes is #277. I just added it.

**Comment by jsonberry** [comment]
Thanks for making #277 I'll put some :eyes: on it

**Comment by knittingcodemonkey** [comment]
Thank you for your help, and your contributions! You're doing great work.

**Comment by jsonberry** [comment]
Per the discussion here @JWO719 , can we close this issue?

I've opened #278 to capture UX improvements when reopening the sidenav.

**Comment by JWO719** [comment]
closing due to #277
